# Generated by Django 4.2.30 on 2026-08-05 14:13

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("warehouse", "0005_productionrun_productionmaterial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyRequisites",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        editable=False,
                        verbose_name="Действующие реквизиты",
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        help_text="Например: ООО «ЛЕКО»",
                        max_length=255,
                        verbose_name="Краткое наименование",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        help_text="Как в уставе: Общество с ограниченной ответственностью…",
                        max_length=500,
                        verbose_name="Полное наименование",
                    ),
                ),
                (
                    "inn",
                    models.CharField(
                        max_length=12,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{10}$|^\\d{12}$",
                                "ИНН состоит из 10 цифр у организации или 12 у предпринимателя",
                            )
                        ],
                        verbose_name="ИНН",
                    ),
                ),
                (
                    "kpp",
                    models.CharField(
                        blank=True,
                        help_text="У индивидуальных предпринимателей КПП нет — оставьте пустым",
                        max_length=9,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{9}$", "КПП состоит из 9 цифр"
                            )
                        ],
                        verbose_name="КПП",
                    ),
                ),
                (
                    "ogrn",
                    models.CharField(blank=True, max_length=15, verbose_name="ОГРН"),
                ),
                (
                    "legal_address",
                    models.CharField(max_length=500, verbose_name="Юридический адрес"),
                ),
                (
                    "postal_address",
                    models.CharField(
                        blank=True,
                        help_text="Заполните, если отличается от юридического",
                        max_length=500,
                        verbose_name="Почтовый адрес",
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=50, verbose_name="Телефон"),
                ),
                ("bank_name", models.CharField(max_length=255, verbose_name="Банк")),
                (
                    "bank_bik",
                    models.CharField(
                        max_length=9,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{9}$", "БИК состоит из 9 цифр"
                            )
                        ],
                        verbose_name="БИК",
                    ),
                ),
                (
                    "settlement_account",
                    models.CharField(
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{20}$", "Номер счёта состоит из 20 цифр"
                            )
                        ],
                        verbose_name="Расчётный счёт",
                    ),
                ),
                (
                    "correspondent_account",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{20}$", "Номер счёта состоит из 20 цифр"
                            )
                        ],
                        verbose_name="Корреспондентский счёт",
                    ),
                ),
                (
                    "director_position",
                    models.CharField(
                        default="Директор",
                        max_length=100,
                        verbose_name="Должность руководителя",
                    ),
                ),
                (
                    "director_name",
                    models.CharField(
                        help_text="Как в подписи: Иванов И. И.",
                        max_length=255,
                        verbose_name="Руководитель",
                    ),
                ),
                (
                    "accountant_name",
                    models.CharField(
                        blank=True,
                        help_text="Оставьте пустым, если обязанности ведёт руководитель",
                        max_length=255,
                        verbose_name="Главный бухгалтер",
                    ),
                ),
                (
                    "vat_rate",
                    models.CharField(
                        choices=[
                            ("20", "НДС 20%"),
                            ("10", "НДС 10%"),
                            ("0", "НДС 0%"),
                            ("none", "Без НДС (УСН)"),
                        ],
                        default="20",
                        max_length=10,
                        verbose_name="Ставка НДС",
                    ),
                ),
                (
                    "vat_included_in_price",
                    models.BooleanField(
                        default=True,
                        help_text="В рознице цена обычно уже включает налог. Если снять галочку, НДС будет начисляться сверх цены товара.",
                        verbose_name="Цены указаны с НДС",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Изменены"),
                ),
            ],
            options={
                "verbose_name": "Реквизиты организации",
                "verbose_name_plural": "Реквизиты организации",
                "db_table": "company_requisites",
            },
        ),
        migrations.CreateModel(
            name="Counterparty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Наименование"
                    ),
                ),
                (
                    "inn",
                    models.CharField(
                        db_index=True,
                        max_length=12,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{10}$|^\\d{12}$",
                                "ИНН состоит из 10 цифр у организации или 12 у предпринимателя",
                            )
                        ],
                        verbose_name="ИНН",
                    ),
                ),
                (
                    "kpp",
                    models.CharField(
                        blank=True,
                        max_length=9,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{9}$", "КПП состоит из 9 цифр"
                            )
                        ],
                        verbose_name="КПП",
                    ),
                ),
                (
                    "legal_address",
                    models.CharField(blank=True, max_length=500, verbose_name="Адрес"),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=50, verbose_name="Телефон"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="E-mail"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Добавлен"),
                ),
            ],
            options={
                "verbose_name": "Покупатель-организация",
                "verbose_name_plural": "Покупатели-организации",
                "db_table": "counterparties",
                "ordering": ["short_name"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Сумма",
                    ),
                ),
                (
                    "paid_at",
                    models.DateField(db_index=True, verbose_name="Дата оплаты"),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("bank", "Банковский перевод"),
                            ("cash", "Наличные"),
                            ("card", "Банковская карта"),
                        ],
                        default="bank",
                        max_length=20,
                        verbose_name="Способ",
                    ),
                ),
                (
                    "document_number",
                    models.CharField(
                        blank=True,
                        help_text="Номер платёжного поручения или чека",
                        max_length=50,
                        verbose_name="Номер платёжного документа",
                    ),
                ),
                (
                    "comment",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Примечание"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Внесена"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Внёс",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="warehouse.order",
                        verbose_name="Заказ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Оплата",
                "verbose_name_plural": "Оплаты",
                "db_table": "payments",
                "ordering": ["-paid_at", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="counterparty",
            constraint=models.UniqueConstraint(
                fields=("inn", "kpp"), name="uniq_counterparty_inn_kpp"
            ),
        ),
        migrations.AddConstraint(
            model_name="companyrequisites",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("is_active",),
                name="uniq_active_company_requisites",
            ),
        ),
    ]
