# Generated by Django 4.2.30 on 2026-07-31 10:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_number', models.CharField(max_length=50, unique=True, verbose_name='Номер')),
                ('doc_date', models.DateField(verbose_name='Дата')),
                ('processed', models.BooleanField(default=False, verbose_name='Проведён')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Приходный документ',
                'verbose_name_plural': 'Приходные документы',
                'db_table': 'inbound_documents',
                'ordering': ['-doc_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('unit', models.CharField(choices=[('pc', 'шт.'), ('kg', 'кг'), ('m', 'м'), ('m2', 'кв. м'), ('l', 'л')], max_length=10, verbose_name='Ед. изм.')),
                ('category', models.CharField(choices=[('textile', 'Ткани'), ('leather', 'Кожа'), ('polymer', 'Полимеры'), ('fittings', 'Фурнитура')], db_index=True, max_length=50, verbose_name='Категория')),
                ('reorder_point', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Минимальный остаток')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
                'db_table': 'materials',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OutboundDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_number', models.CharField(max_length=50, unique=True, verbose_name='Номер')),
                ('doc_date', models.DateField(verbose_name='Дата')),
                ('purpose', models.CharField(choices=[('production', 'В производство'), ('sale', 'На продажу'), ('writeoff', 'Списание')], max_length=20, verbose_name='Назначение')),
                ('production_order', models.CharField(blank=True, max_length=50, verbose_name='Производственный заказ')),
                ('processed', models.BooleanField(default=False, verbose_name='Проведён')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Расходный документ',
                'verbose_name_plural': 'Расходные документы',
                'db_table': 'outbound_documents',
                'ordering': ['-doc_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_number', models.CharField(max_length=50, unique=True, verbose_name='Артикул')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Наименование')),
                ('category', models.CharField(choices=[('shoes', 'Обувь'), ('clothing', 'Одежда'), ('accessories', 'Аксессуары'), ('equipment', 'Инвентарь')], db_index=True, max_length=50, verbose_name='Категория')),
                ('size', models.CharField(max_length=10, verbose_name='Размер')),
                ('color', models.CharField(max_length=50, verbose_name='Цвет')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Себестоимость')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Отпускная цена')),
                ('status', models.CharField(choices=[('active', 'Выпускается'), ('archived', 'Снят с производства')], default='active', max_length=20, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Готовая продукция',
                'verbose_name_plural': 'Готовая продукция',
                'db_table': 'products',
                'ordering': ['name', 'size'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Наименование')),
                ('inn', models.CharField(blank=True, max_length=12, verbose_name='ИНН')),
                ('contact_person', models.CharField(blank=True, max_length=255, verbose_name='Контактное лицо')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
                'db_table': 'suppliers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('type', models.CharField(choices=[('raw', 'Склад сырья'), ('finished', 'Склад готовой продукции')], max_length=20, verbose_name='Тип')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Расположение')),
                ('capacity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Вместимость')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склады',
                'db_table': 'warehouses',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('in', 'Приход'), ('out', 'Расход'), ('adjust', 'Корректировка')], max_length=10, verbose_name='Тип')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Количество')),
                ('document_id', models.IntegerField(blank=True, null=True, verbose_name='ID документа')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата и время')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.material')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.warehouse')),
            ],
            options={
                'verbose_name': 'Движение товара',
                'verbose_name_plural': 'Журнал движения',
                'db_table': 'stock_movements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Остаток')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='warehouse.material')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='warehouse.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='warehouse.warehouse')),
            ],
            options={
                'verbose_name': 'Остаток на складе',
                'verbose_name_plural': 'Остатки на складах',
                'db_table': 'stock',
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='Зафиксирована')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='warehouse.material')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='warehouse.product')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.supplier')),
            ],
            options={
                'verbose_name': 'История цены',
                'verbose_name_plural': 'История закупочных цен',
                'db_table': 'price_history',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='OutboundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена за единицу')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='warehouse.material')),
                ('outbound_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warehouse.outbounddocument')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='warehouse.product')),
            ],
            options={
                'verbose_name': 'Строка расхода',
                'verbose_name_plural': 'Строки расхода',
                'db_table': 'outbound_items',
            },
        ),
        migrations.AddField(
            model_name='outbounddocument',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.warehouse', verbose_name='Склад'),
        ),
        migrations.CreateModel(
            name='InboundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена за единицу')),
                ('batch_number', models.CharField(blank=True, max_length=50, verbose_name='Партия')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Срок годности')),
                ('inbound_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warehouse.inbounddocument')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='warehouse.material')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='warehouse.product')),
            ],
            options={
                'verbose_name': 'Строка прихода',
                'verbose_name_plural': 'Строки прихода',
                'db_table': 'inbound_items',
            },
        ),
        migrations.AddField(
            model_name='inbounddocument',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.supplier', verbose_name='Поставщик'),
        ),
        migrations.AddField(
            model_name='inbounddocument',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.warehouse', verbose_name='Склад'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.UniqueConstraint(fields=('warehouse', 'material', 'product'), name='uniq_stock_position'),
        ),
        migrations.AddConstraint(
            model_name='outbounditem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('material__isnull', False), ('product__isnull', True)), models.Q(('material__isnull', True), ('product__isnull', False)), _connector='OR'), name='outbound_item_material_xor_product'),
        ),
        migrations.AddConstraint(
            model_name='inbounditem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('material__isnull', False), ('product__isnull', True)), models.Q(('material__isnull', True), ('product__isnull', False)), _connector='OR'), name='inbound_item_material_xor_product'),
        ),
    ]
