# Generated by Django 4.2.30 on 2026-08-01 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='article_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Артикул'),
        ),
        migrations.AddField(
            model_name='material',
            name='color',
            field=models.CharField(blank=True, max_length=50, verbose_name='Цвет'),
        ),
    ]
