# Generated by Django 6.0.8 on 2026-08-05 21:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0004_alter_product_photo_order_orderitem"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductionRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(max_length=50, unique=True, verbose_name="Номер"),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Количество",
                    ),
                ),
                (
                    "material_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Стоимость материалов",
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Себестоимость единицы",
                    ),
                ),
                (
                    "planned_unit_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Значение из карточки товара на момент выпуска",
                        max_digits=12,
                        verbose_name="Плановая себестоимость единицы",
                    ),
                ),
                (
                    "pricing_complete",
                    models.BooleanField(
                        default=True,
                        help_text="Снимается, если по какому-то материалу не было ни одной закупки — тогда себестоимость занижена",
                        verbose_name="Цены известны по всем материалам",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Выпущено"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Выпустил",
                    ),
                ),
                (
                    "material_warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="production_input",
                        to="warehouse.warehouse",
                        verbose_name="Склад материалов",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="production_runs",
                        to="warehouse.product",
                        verbose_name="Продукция",
                    ),
                ),
                (
                    "product_warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="production_output",
                        to="warehouse.warehouse",
                        verbose_name="Склад продукции",
                    ),
                ),
            ],
            options={
                "verbose_name": "Выпуск продукции",
                "verbose_name_plural": "Выпуски продукции",
                "db_table": "production_runs",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ProductionMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Количество"
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Цена за единицу",
                    ),
                ),
                (
                    "price_known",
                    models.BooleanField(
                        default=True,
                        help_text="Ложь, если по материалу не было ни одной закупки",
                        verbose_name="Цена известна",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="warehouse.material",
                        verbose_name="Материал",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="warehouse.productionrun",
                    ),
                ),
            ],
            options={
                "verbose_name": "Материал выпуска",
                "verbose_name_plural": "Материалы выпуска",
                "db_table": "production_materials",
            },
        ),
    ]
