# Generated by Django 6.0.8 on 2026-08-11 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
        ("warehouse", "0005_productionrun_productionmaterial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="counterparty",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="billing.counterparty",
                verbose_name="Покупатель-организация",
            ),
        ),
    ]
