# Generated by Django 4.2.30 on 2026-08-05 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
        ("warehouse", "0005_stock_unique_and_xor_constraints"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="counterparty",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="billing.counterparty",
                verbose_name="Покупатель-организация",
            ),
        ),
    ]
