# Generated by Django 6.0.8 on 2026-08-11 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0006_order_counterparty"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="created_ip",
            field=models.GenericIPAddressField(
                blank=True, null=True, verbose_name="Адрес, откуда оформлен"
            ),
        ),
    ]
