# Generated by Django 5.2.17 on 2026-08-12 00:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0008_inbounddocument_deleted_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="inbounddocument",
            name="doc_number",
            field=models.CharField(db_index=True, max_length=50, verbose_name="Номер"),
        ),
        migrations.AlterField(
            model_name="outbounddocument",
            name="doc_number",
            field=models.CharField(db_index=True, max_length=50, verbose_name="Номер"),
        ),
        migrations.AddConstraint(
            model_name="inbounddocument",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("doc_number",),
                name="inbound_number_unique_among_live",
            ),
        ),
        migrations.AddConstraint(
            model_name="outbounddocument",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("doc_number",),
                name="outbound_number_unique_among_live",
            ),
        ),
    ]
