# Generated by Django 5.2.17 on 2026-08-12 00:13

from django.db import migrations, models


def add_builtin_units(apps, schema_editor):
    """Перенести встроенные пять единиц в таблицу.

    До этого они жили только в коде. База уже полна материалов с этими
    кодами, поэтому строки должны появиться раньше, чем кто-нибудь
    откроет справочник, — иначе в списках вместо «кг» окажется «kg».
    """
    Unit = apps.get_model('warehouse', 'Unit')
    builtin = [
        ('pc', 'шт.', 'Штука', '796'),
        ('kg', 'кг', 'Килограмм', '166'),
        ('m', 'м', 'Метр', '006'),
        ('m2', 'кв. м', 'Квадратный метр', '055'),
        ('l', 'л', 'Литр', '112'),
    ]
    for number, (code, name, full_name, okei) in enumerate(builtin):
        Unit.objects.update_or_create(
            code=code,
            defaults={'name': name, 'full_name': full_name, 'okei': okei,
                      'builtin': True, 'sort_order': number})


def remove_builtin_units(apps, schema_editor):
    Unit = apps.get_model('warehouse', 'Unit')
    Unit.objects.filter(builtin=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0009_alter_inbounddocument_doc_number_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=10, unique=True, verbose_name="Код"),
                ),
                ("name", models.CharField(max_length=20, verbose_name="Обозначение")),
                (
                    "full_name",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Полное название"
                    ),
                ),
                (
                    "okei",
                    models.CharField(blank=True, max_length=4, verbose_name="Код ОКЕИ"),
                ),
                (
                    "builtin",
                    models.BooleanField(default=False, verbose_name="Встроенная"),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=100, verbose_name="Порядок"
                    ),
                ),
            ],
            options={
                "verbose_name": "Единица измерения",
                "verbose_name_plural": "Единицы измерения",
                "db_table": "units",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.AlterField(
            model_name="material",
            name="unit",
            field=models.CharField(max_length=10, verbose_name="Ед. изм."),
        ),
        migrations.RunPython(add_builtin_units, remove_builtin_units),
    ]
