# Generated by Django 5.2.17 on 2026-08-12 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0011_product_photos"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="barcode",
            field=models.CharField(
                blank=True, db_index=True, max_length=32, verbose_name="Штрихкод"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="barcode",
            field=models.CharField(
                blank=True, db_index=True, max_length=32, verbose_name="Штрихкод"
            ),
        ),
    ]
