# Generated by Django 5.2.17 on 2026-09-09 13:07

from django.db import migrations, models


def merge_duplicate_stock(apps, schema_editor):
    """Слить раздвоившиеся строки остатка перед установкой запрета.

    Прежнее ограничение дублей не ловило (пояснение — в модели Stock),
    поэтому в базе, где два прихода однажды сошлись на одной позиции,
    такие строки уже могут лежать. Пока они там, база не даст завести
    новый запрет, и обновление остановится на полпути.

    Складываем количество в самую раннюю строку позиции, остальные
    убираем. Складываем, а не выбираем одну: обе половины — настоящий
    товар, оприходованный разными документами, и потерять любую значит
    занизить остаток. Движения в журнале трогать не нужно — они и
    описывают, из чего сложилась сумма.
    """
    Stock = apps.get_model('warehouse', 'Stock')

    first_of = {}
    merged = {}
    duplicates = []
    for row in Stock.objects.order_by('id').iterator():
        key = (row.warehouse_id, row.material_id, row.product_id)
        first = first_of.get(key)
        if first is None:
            first_of[key] = row
        else:
            total = merged.get(first.pk, first.quantity)
            merged[first.pk] = total + row.quantity
            duplicates.append(row.pk)

    for pk, quantity in merged.items():
        Stock.objects.filter(pk=pk).update(quantity=quantity)
    if duplicates:
        Stock.objects.filter(pk__in=duplicates).delete()


def unmerge_noop(apps, schema_editor):
    """Обратного хода нет: разделить сложенное количество не по чему.

    Пустая функция нужна, чтобы миграция откатывалась — снятие запрета
    само по себе безопасно, а слитые строки так и останутся слитыми.
    """


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0012_barcodes"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="stock",
            name="uniq_stock_position",
        ),
        migrations.RunPython(merge_duplicate_stock, unmerge_noop),
        migrations.AddConstraint(
            model_name="stock",
            constraint=models.UniqueConstraint(
                condition=models.Q(("product__isnull", True)),
                fields=("warehouse", "material"),
                name="uniq_stock_material",
            ),
        ),
        migrations.AddConstraint(
            model_name="stock",
            constraint=models.UniqueConstraint(
                condition=models.Q(("material__isnull", True)),
                fields=("warehouse", "product"),
                name="uniq_stock_product",
            ),
        ),
    ]
