# Generated by Django 4.2.30 on 2026-08-04 08:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatReadState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_read_id', models.PositiveIntegerField(default=0, verbose_name='Последнее прочитанное сообщение')),
                ('peer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_read_by', to=settings.AUTH_USER_MODEL, verbose_name='Собеседник')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_read_states', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Отметка прочтения чата',
                'verbose_name_plural': 'Отметки прочтения чата',
                'db_table': 'chat_read_state',
            },
        ),
        migrations.AddConstraint(
            model_name='chatreadstate',
            constraint=models.UniqueConstraint(condition=models.Q(('peer__isnull', False)), fields=('user', 'peer'), name='uniq_chat_read_private'),
        ),
        migrations.AddConstraint(
            model_name='chatreadstate',
            constraint=models.UniqueConstraint(condition=models.Q(('peer__isnull', True)), fields=('user',), name='uniq_chat_read_general'),
        ),
    ]
