# Generated by Django 6.0.8 on 2026-08-07 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "happened_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Когда"
                    ),
                ),
                (
                    "user_label",
                    models.CharField(
                        blank=True,
                        help_text="Как звали пользователя на момент действия",
                        max_length=200,
                        verbose_name="Кто (текстом)",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Создание"),
                            ("change", "Изменение"),
                            ("delete", "Удаление"),
                        ],
                        db_index=True,
                        max_length=10,
                        verbose_name="Действие",
                    ),
                ),
                (
                    "model_label",
                    models.CharField(
                        db_index=True,
                        help_text="Например, warehouse.Material",
                        max_length=100,
                        verbose_name="Что за запись",
                    ),
                ),
                (
                    "model_title",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Вид записи"
                    ),
                ),
                (
                    "object_id",
                    models.PositiveBigIntegerField(
                        null=True, verbose_name="Номер записи"
                    ),
                ),
                (
                    "object_label",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Название записи"
                    ),
                ),
                (
                    "changes",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Что изменилось"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_entries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись журнала",
                "verbose_name_plural": "Журнал действий",
                "db_table": "audit_entries",
                "ordering": ["-happened_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["model_label", "object_id"], name="audit_object_idx"
                    )
                ],
            },
        ),
    ]
